# metadata.py

import json

def create_metadata(title, description, artist, creation_date, file_path, wallet_address,sender_ip,sender_port):
    metadata = {
        "title": title,
        "description": description,
        "artist": artist,
        "creation_date": creation_date,
        "file_path": file_path,
        "wallet_address": wallet_address,  # Include wallet address in metadata
        "sender_ip": sender_ip,
        "sender_port": sender_port
    }
   
    return metadata

# Example metadata for the artwork
title = "Mountain"
description = "Beautiful Mountain"
artist = "Sid"
creation_date = "2024-04-21"
file_path = "encrypted_image.enc"
sender_ip = "192.168.137.56"
sender_port = 8080

# Read wallet address from the JSON file generated by generate_pc1_details()
with open('pc1_details.json', 'r') as f:
    pc1_details = json.load(f)
    wallet_address = pc1_details['wallet_address']

# Create metadata
metadata = create_metadata(title, description, artist, creation_date, file_path, wallet_address,sender_ip,sender_port)

# Save metadata to a JSON file
with open('nft_metadata_pc1.json', 'w') as f:
    json.dump(metadata, f)
print(metadata)
print("NFT metadata saved successfully.")